pipeline {
    agent none

    stages {
        stage('Run on All Nodes') {
            matrix {
                axes {
                    axis {
                        name 'NODE'
                        values 'debian13-1', 'debian13-2'
                    }
                }
                agent {
                    node "${NODE}"
                }
                stages {
                    stage('Checkout') {
                        steps {
                            checkout scm
                        }
                    }

                    stage('Ping Test') {
                        steps {
                            script {
                                echo "Node Execution: ${env.NODE_NAME}"

                                sh 'ping -c 4 google.ro'
                            }
                        }
                    }

                    stage('Cleanup After') {
                        steps {
                            cleanWs()
                        }
                    }
                }
            }
        }
    }
}
